POST http://localhost:5278/api/ShoppingLists
Content-Type: application/json

{
  "name" : "Steam Winter Sale"
}

###

GET http://localhost:5278/api/ShoppingLists

###

GET http://localhost:5278/api/ShoppingLists/2

###

PUT http://localhost:5278/api/ShoppingLists/1
Content-Type: application/json

{
  "id" : 1,
  "name": "Sint Nicholaas"
}