POST http://localhost:5278/api/ShoppingLists
Content-Type: application/json

{
  "name" : "Groceries"
}

###

GET http://localhost:5278/api/ShoppingLists

###

GET http://localhost:5278/api/ShoppingLists/2