// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WardrobeInventory.Blazor.Data;

#nullable disable

namespace WardrobeInventory.Blazor.Migrations
{
    [DbContext(typeof(WardrobeContext))]
    [Migration("20260120115404_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WardrobeInventory.Blazor.Models.WardrobeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("BLOB");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WardrobeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BrandA",
                            Category = 0,
                            Name = "Shirt",
                            Size = 0
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BrandB",
                            Category = 1,
                            Name = "Pants",
                            Size = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "BrandC",
                            Category = 3,
                            Name = "Shoes",
                            Size = 2
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BrandD",
                            Category = 2,
                            Name = "Dress",
                            Size = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
